import type { Metadata } from 'next';
import { Karla } from 'next/font/google';
import './globals.css';
import { MainLayout } from '@/components/layouts';
import { Toaster, toast } from 'sonner';

const karla = Karla({
  subsets: ['latin', 'latin-ext'],
  variable: '--font-karla',
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Argos Store Template',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${karla.className} ${karla.variable} scroll-smooth! antialiased`}>
        <Toaster richColors />
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
